/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.clientes.dao;

import java.util.List;
import java.util.Map;
import java.util.List;
import com.lix.dao.HibernateDao;
import com.lix.clientes.model.Clientes;


/**
 * Basic persistence operations for entity "Clientes"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface ClientesDao extends HibernateDao<Clientes,Integer> {	

	public List<Clientes> findByName(String name);
}
