/*
 * Created on 20 jul 2014 ( Time 08:21:38 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.domain.master.usuariosproductores.dto;

import java.io.Serializable;

import com.lix.domain.master.usuariosproductores.dto.*;
import com.lix.dto.PaginationParams;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;



/**
 * Dto for "UsuariosProductores"
 *
 * @author Telosys Tools Generator
 *
 */
public class UsuariosProductoresDto extends PaginationParams
{
    


		    private Integer id          ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
			    private Integer userId;

			    private Integer productorId;

    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : USER_ID ( INT ) 
    public void setUserId( Integer userId )
    {
        this.userId = userId;
    }
    public Integer getUserId()
    {
        return this.userId;
    }

    //--- DATABASE MAPPING : PRODUCTOR_ID ( INT ) 
    public void setProductorId( Integer productorId )
    {
        this.productorId = productorId;
    }
    public Integer getProductorId()
    {
        return this.productorId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		return "";
		//return ReflectionToStringBuilder.toString(this);
    }

}
