/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.secciones.service;

import java.util.List;
import java.util.Map;

import com.lix.secciones.model.Secciones;
import com.lix.service.Service;
import com.lix.secciones.dto.SeccionesDto;
import com.lix.dto.DefaultResponse;

/**
 * Basic persistence operations for entity "Secciones"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface SeccionesService extends Service<Secciones,Integer>{
	DefaultResponse createOrUpdate(SeccionesDto dto);
	List<Secciones> findByName(String name);
}
