/*
 * Created on 28 nov 2013 ( Time 16:19:02 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.polizas.dao;

import java.util.List;

import com.lix.dao.HibernateDao;
import com.lix.polizas.dto.PolizasDto;
import com.lix.polizas.dto.PolizasPorVencerDto;
import com.lix.polizas.model.Polizas;
import com.lix.web.Page;

/**
 * Basic persistence operations for entity "Polizas"
 * 
 * 
 * @author Telosys Tools Generator
 * 
 */
public interface PolizasDao extends HibernateDao<Polizas, Integer> {

	public List<Polizas> findByName(String name);

	public List<Polizas> polizasPorCliente(Integer id);

	public Page<PolizasDto> findPage(PolizasDto dto);

	Page<PolizasDto> getPolizasPorVencerPage(PolizasPorVencerDto dto);

	public List<Polizas> getPolizasPorVencerList(PolizasPorVencerDto dto);

}
