/*
 * Created on 28 nov 2013 ( Time 16:19:02 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.polizas.dao;

import java.util.Date;
import java.util.List;

import com.lix.dao.HibernateDao;
import com.lix.polizas.model.Polizas;

/**
 * Basic persistence operations for entity "Polizas"
 * 
 * 
 * @author Telosys Tools Generator
 * 
 */
public interface PolizasDao extends HibernateDao<Polizas, Integer> {

	public List<Polizas> findByName(String name);

	public List<Polizas> polizasPorCliente(Integer id);

	public List<Polizas> getPolizasPorVencer(Date fechaDesde, Date fechaHasta);

}
