/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.lix.secciones.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.lix.dto.DefaultResponse;
import com.lix.dto.PaginationParams;
import com.lix.secciones.dao.SeccionesDao;
import com.lix.secciones.dto.SeccionesDto;
import com.lix.secciones.model.Secciones;
import com.lix.secciones.service.SeccionesService;
import com.lix.util.BeanUtils;

/**
 * JPA implementation for basic persistence operations ( entity "Secciones" )
 * 
 * @author Telosys Tools Generator
 * 
 */

@Component("seccionesService")
public class SeccionesServiceImpl implements SeccionesService {

	@Autowired
	SeccionesDao seccionesDao;

	@Override
	public void save(Secciones entity) {
		seccionesDao.save(entity);
	}

	@Override
	public Secciones update(Secciones entity) {
		return seccionesDao.update(entity);

	}

	@Override
	public void delete(Secciones entity) {
		seccionesDao.delete(entity);

	}

	@Override
	public List<Secciones> findAll() {
		return seccionesDao.findAll();
	}

	@Override
	public Secciones getById(Integer id) {
		return seccionesDao.findOne(id);
	}

	@Override
	public void deleteById(Integer id) {
		seccionesDao.deleteById(id);

	}

	@Override
	public DefaultResponse createOrUpdate(SeccionesDto dto) {
		DefaultResponse response = new DefaultResponse();
		try {
			Secciones ent = BeanUtils.copyProperties(dto, Secciones.class);
			ent = this.update(ent);
			response.setId(ent.getId());
		} catch (Exception e) {
			response.setSuccess(false);
			response.setMessage(e.getMessage());
		}
		return response;
	}

	@Override
	public List<Secciones> findByName(String name) {
		return seccionesDao.findByName(name);

	}

	@Override
	public List<Secciones> getPage(PaginationParams params) {
		return seccionesDao.getPage(params);
	}

}
