/*
 * Created on 14 nov 2013 ( Time 17:20:08 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.secciones.dao.impl;

import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.Criteria;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;

import com.lix.secciones.model.Secciones;
import com.lix.secciones.dao.SeccionesDao;
import com.lix.dao.AbstractHibernateDao;

/**
 * Basic persistence operations for entity "Secciones"
 * 
 *
 * @author Lisandro
 *
 */
@Repository("seccionesDao")
public class SeccionesDaoImpl extends AbstractHibernateDao<Secciones,Integer> implements SeccionesDao{

	@PostConstruct
	public void setInstance() {
		setClazz(Secciones.class);
	}
	@Override
	@Transactional
	public List<Secciones> findByName(String name) {
		Criteria criteria = getCurrentSession().createCriteria((Secciones.class));
		criteria.add(Restrictions.like("name", name.toUpperCase(), MatchMode.ANYWHERE));
		return (List<Secciones>) criteria.list();
	}
}
