/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.companias;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import com.lix.companias.model.Companias;
import com.lix.companias.service.CompaniasService;
import com.lix.test.AbstractTestWithContext;

/**
 * JUnit test case for Companias persistence service
 * 
 * @author Telosys Tools Generator
 * 
 */
public class CompaniasTest extends AbstractTestWithContext {
	@Autowired
	CompaniasService service;

	@Test
	public void findAll() {
		List<Companias> list = service.findAll();
		Assert.assertTrue(list.size() > 0);
	}
}
