/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.clientes.dto;

import java.util.Date;
import java.util.List;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.lix.polizas.model.Polizas;
import com.lix.util.JsonDateSerializer;

/**
 * Dto for "Clientes"
 * 
 * @author Telosys Tools Generator
 * 
 */
public class ClientesDto {

	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	private String nombre;

	private String apellido;

	private String direccion;

	private String telefono;

	private String email;

	private String observaciones;

	@JsonSerialize(using = JsonDateSerializer.class)
	private Date fNacimiento;

	private String dnicuit;

	private List<Polizas> polizas;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : nombre ( VARCHAR )
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	// --- DATABASE MAPPING : apellido ( VARCHAR )
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getApellido() {
		return this.apellido;
	}

	// --- DATABASE MAPPING : direccion ( VARCHAR )
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	// --- DATABASE MAPPING : telefono ( VARCHAR )
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getTelefono() {
		return this.telefono;
	}

	// --- DATABASE MAPPING : email ( VARCHAR )
	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return this.email;
	}

	// --- DATABASE MAPPING : observaciones ( VARCHAR )
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	// --- DATABASE MAPPING : f_nacimiento ( DATETIME )
	public void setFNacimiento(Date fNacimiento) {
		this.fNacimiento = fNacimiento;
	}

	public Date getFNacimiento() {
		return this.fNacimiento;
	}

	// --- DATABASE MAPPING : DNICUIT ( VARCHAR )
	public void setDnicuit(String dnicuit) {
		this.dnicuit = dnicuit;
	}

	public String getDnicuit() {
		return this.dnicuit;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	public void setListOfPolizas(List<Polizas> listOfPolizas) {
		this.polizas = listOfPolizas;
	}

	public List<Polizas> getListOfPolizas() {
		return this.polizas;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

}
