
/*
 * Created on 6 dic 2013 ( Time 23:51:34 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.companias;

import java.util.LinkedList;
import java.util.List;

import com.lix.companias.model.Companias;
import com.lix.mock.tool.MockValues;

public class CompaniasMock {

	private static MockValues mockValues = new MockValues();
	
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public static  Companias createInstance() {
		Companias entity = new Companias();

		// Init Data fields
		entity.setNombre( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setPagos( TODO ) ; // List<PagosCompanias> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public static List<Companias> createList(int count) {
		List<Companias> list = new LinkedList<Companias>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}	
	
}
