/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.clientes.service;

import java.util.List;
import java.util.Map;

import com.lix.clientes.model.Clientes;
import com.lix.service.Service;
import com.lix.clientes.dto.ClientesDto;
import com.lix.dto.DefaultResponse;

/**
 * Basic persistence operations for entity "Clientes"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface ClientesService extends Service<Clientes,Integer>{
	DefaultResponse createOrUpdate(ClientesDto dto);
	List<Clientes> findByName(String name);
}
