/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.companias.dto;

import java.util.List;

import com.lix.dto.PaginationParams;
import com.lix.pagos.model.Pagos;
import com.lix.polizas.model.Polizas;

/**
 * Dto for "Companias"
 * 
 * @author Telosys Tools Generator
 * 
 */
public class CompaniasDto extends PaginationParams {

	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	private String nombre;

	private List<Pagos> listOfPagos;

	private List<Polizas> listOfPolizas;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : NOMBRE ( VARCHAR )
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	public void setListOfPagos(List<Pagos> listOfPagos) {
		this.listOfPagos = listOfPagos;
	}

	public List<Pagos> getListOfPagos() {
		return this.listOfPagos;
	}

	public void setListOfPolizas(List<Polizas> listOfPolizas) {
		this.listOfPolizas = listOfPolizas;
	}

	public List<Polizas> getListOfPolizas() {
		return this.listOfPolizas;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

}
