/*
 * Created on 28 nov 2013 ( Time 16:18:58 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.polizas.service;

import java.util.List;

import com.lix.dto.DefaultResponse;
import com.lix.polizas.dto.PolizasDto;
import com.lix.polizas.dto.PolizasPorVencerDto;
import com.lix.polizas.model.Polizas;
import com.lix.service.Service;

/**
 * Basic persistence operations for entity "Polizas"
 * 
 * 
 * @author Telosys Tools Generator
 * 
 */
public interface PolizasService extends Service<Polizas,Integer>{
	DefaultResponse createOrUpdate(PolizasDto dto);

	List<Polizas> findByName(String name);

	List<Polizas> polizasPorCliente(Integer id);

	List<Polizas> getPolizasPorVencer(PolizasPorVencerDto dto);
}
