/*
 * Created on 28 nov 2013 ( Time 16:18:58 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.lix.polizas.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.lix.dto.DefaultResponse;
import com.lix.polizas.dao.PolizasDao;
import com.lix.polizas.dto.PolizasDto;
import com.lix.polizas.dto.PolizasPorVencerDto;
import com.lix.polizas.model.Polizas;
import com.lix.polizas.service.PolizasService;
import com.lix.service.GenericService;
import com.lix.util.BeanUtils;
import com.lix.web.Page;

/**
 * JPA implementation for basic persistence operations ( entity "Polizas" )
 * 
 * @author Telosys Tools Generator
 * 
 */

@Component("polizasService")
public class PolizasServiceImpl extends GenericService<Polizas, Integer>
		implements PolizasService {

	@Autowired
	PolizasDao polizasDao;

	@Override
	public DefaultResponse createOrUpdate(PolizasDto dto) {
		DefaultResponse response = new DefaultResponse();
		try {
			Polizas ent = BeanUtils.mapper.map(dto, Polizas.class);
			ent = this.update(ent);
			response.setId(ent.getId());
		} catch (Exception e) {
			response.setSuccess(false);
			response.setMessage(e.getMessage());
		}
		return response;
	}

	@Override
	public List<Polizas> findByName(String name) {
		return polizasDao.findByName(name);

	}

	@Override
	public List<Polizas> polizasPorCliente(Integer id) {
		return polizasDao.polizasPorCliente(id);
	}

	@Override
	public void setDao() {
		this.dao = polizasDao;

	}

	@Override
	public List<Polizas> getPolizasPorVencer(PolizasPorVencerDto dto) {
		return polizasDao.getPolizasPorVencer(dto.getFechaDesde(),
				dto.getFechaHasta());
	}

	@Override
	@Transactional
	public Page<PolizasDto> findPage(PolizasDto dto) {
		return polizasDao.findPage(dto);
	}
}
