/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.pagos.dao;

import java.util.List;
import java.util.Map;
import java.util.List;
import com.lix.dao.HibernateDao;
import com.lix.pagos.model.Pagos;


/**
 * Basic persistence operations for entity "Pagos"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface PagosDao extends HibernateDao<Pagos,Integer> {	

	public List<Pagos> findByName(String name);
}
