/*
 * Created on 28 nov 2013 ( Time 16:19:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.polizas.dto;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.lix.clientes.dto.ClientesDto;
import com.lix.companias.dto.CompaniasDto;
import com.lix.secciones.dto.SeccionesDto;
import com.lix.util.JsonDateSerializer;

/**
 * Dto for "Polizas"
 * 
 * @author Telosys Tools Generator
 * 
 */
public class PolizasDto {

	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	private String nroPoliza;

	private String endoso;

	private String observaciones;
	@JsonSerialize(using = JsonDateSerializer.class)
	private Date fVigDesde;
	@JsonSerialize(using = JsonDateSerializer.class)
	private Date fVigHasta;

	@JsonSerialize(using = JsonDateSerializer.class)
	private Date fRegistracion;

	private Integer cantCuotas;

	private Double prima;

	private Double suma;

	private Double premio;

	private SeccionesDto tipoPoliza;

	private String bienACubrir;

	private String moneda;

	private String riesgoACubrir;

	// private String clasePoliza;

	private String ubicacion;

	private String nroChasis;

	private String nroMotor;

	private String tipoCobertura;

	private Integer orden;

	private String patente;

	private CompaniasDto companias;

	private SeccionesDto secciones;

	// private List<PagosPolizasDto> pagosPolizas;

	private ClientesDto clientes;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : NRO_POLIZA ( VARCHAR )
	public void setNroPoliza(String nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	public String getNroPoliza() {
		return this.nroPoliza;
	}

	// --- DATABASE MAPPING : ENDOSO ( VARCHAR )
	public void setEndoso(String endoso) {
		this.endoso = endoso;
	}

	public String getEndoso() {
		return this.endoso;
	}

	// --- DATABASE MAPPING : OBSERVACIONES ( VARCHAR )
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	// --- DATABASE MAPPING : F_VIG_DESDE ( DATETIME )
	public void setFVigDesde(Date fVigDesde) {
		this.fVigDesde = fVigDesde;
	}

	public Date getFVigDesde() {
		return this.fVigDesde;
	}

	// --- DATABASE MAPPING : F_VIG_HASTA ( DATETIME )
	public void setFVigHasta(Date fVigHasta) {
		this.fVigHasta = fVigHasta;
	}

	public Date getFVigHasta() {
		return this.fVigHasta;
	}

	// --- DATABASE MAPPING : CANT_CUOTAS ( INT )
	public void setCantCuotas(Integer cantCuotas) {
		this.cantCuotas = cantCuotas;
	}

	public Integer getCantCuotas() {
		return this.cantCuotas;
	}

	// --- DATABASE MAPPING : PRIMA ( DOUBLE )
	public void setPrima(Double prima) {
		this.prima = prima;
	}

	public Double getPrima() {
		return this.prima;
	}

	// --- DATABASE MAPPING : SUMA ( DOUBLE )
	public void setSuma(Double suma) {
		this.suma = suma;
	}

	public Double getSuma() {
		return this.suma;
	}

	// --- DATABASE MAPPING : PREMIO ( DOUBLE )
	public void setPremio(Double premio) {
		this.premio = premio;
	}

	public Double getPremio() {
		return this.premio;
	}

	// --- DATABASE MAPPING : TIPO_POLIZA ( VARCHAR )
	public void setTipoPoliza(SeccionesDto tipoPoliza) {
		this.tipoPoliza = tipoPoliza;
	}

	public SeccionesDto getTipoPoliza() {
		return this.tipoPoliza;
	}

	// --- DATABASE MAPPING : BIEN_A_CUBRIR ( VARCHAR )
	public void setBienACubrir(String bienACubrir) {
		this.bienACubrir = bienACubrir;
	}

	public String getBienACubrir() {
		return this.bienACubrir;
	}

	// --- DATABASE MAPPING : MONEDA ( VARCHAR )
	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getMoneda() {
		return this.moneda;
	}

	// --- DATABASE MAPPING : RIESGO_A_CUBRIR ( VARCHAR )
	public void setRiesgoACubrir(String riesgoACubrir) {
		this.riesgoACubrir = riesgoACubrir;
	}

	public String getRiesgoACubrir() {
		return this.riesgoACubrir;
	}

	// --- DATABASE MAPPING : CLASE_POLIZA ( VARCHAR )
	// public void setClasePoliza(String clasePoliza) {
	// this.clasePoliza = clasePoliza;
	// }
	//
	// public String getClasePoliza() {
	// return this.clasePoliza;
	// }

	// --- DATABASE MAPPING : UBICACION ( VARCHAR )
	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	// --- DATABASE MAPPING : NRO_CHASIS ( VARCHAR )
	public void setNroChasis(String nroChasis) {
		this.nroChasis = nroChasis;
	}

	public String getNroChasis() {
		return this.nroChasis;
	}

	// --- DATABASE MAPPING : NRO_MOTOR ( VARCHAR )
	public void setNroMotor(String nroMotor) {
		this.nroMotor = nroMotor;
	}

	public String getNroMotor() {
		return this.nroMotor;
	}

	// --- DATABASE MAPPING : TIPO_COBERTURA ( VARCHAR )
	public void setTipoCobertura(String tipoCobertura) {
		this.tipoCobertura = tipoCobertura;
	}

	public String getTipoCobertura() {
		return this.tipoCobertura;
	}

	// --- DATABASE MAPPING : f_registracion ( DATETIME )
	public void setFRegistracion(Date fRegistracion) {
		this.fRegistracion = fRegistracion;
	}

	public Date getFRegistracion() {
		return this.fRegistracion;
	}

	// --- DATABASE MAPPING : ORDEN ( INT )
	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Integer getOrden() {
		return this.orden;
	}

	// --- DATABASE MAPPING : PATENTE ( VARCHAR )
	public void setPatente(String patente) {
		this.patente = patente;
	}

	public String getPatente() {
		return this.patente;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	public void setCompanias(CompaniasDto companias) {
		this.companias = companias;
	}

	public CompaniasDto getCompanias() {
		return this.companias;
	}

	public void setSecciones(SeccionesDto secciones) {
		this.secciones = secciones;
	}

	public SeccionesDto getSecciones() {
		return this.secciones;
	}

	// public void setPagosPolizas(List<PagosPolizasDto> pagosPolizas) {
	// this.pagosPolizas = pagosPolizas;
	// }
	//
	// public List<PagosPolizasDto> getPagosPolizas() {
	// return this.pagosPolizas;
	// }

	public void setClientes(ClientesDto clientes) {
		this.clientes = clientes;
	}

	public ClientesDto getClientes() {
		return this.clientes;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

}
