/*
 * Created on 27 nov 2013 ( Time 16:23:13 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.lix.pagoscompanias.service.impl;

import java.util.List;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.lix.dto.DefaultResponse;
import com.lix.dto.PaginationParams;
import com.lix.pagoscompanias.dao.PagosCompaniasDao;
import com.lix.pagoscompanias.dto.PagosCompaniasDto;
import com.lix.pagoscompanias.model.PagosCompanias;
import com.lix.pagoscompanias.service.PagosCompaniasService;

/**
 * JPA implementation for basic persistence operations ( entity "PagosCompanias" )
 * 
 * @author Telosys Tools Generator
 * 
 */

@Component("pagoscompaniasService")
public class PagosCompaniasServiceImpl implements PagosCompaniasService {

	@Autowired
	PagosCompaniasDao pagoscompaniasDao;

	@Override
	public void save(PagosCompanias entity) {
		pagoscompaniasDao.save(entity);
	}

	@Override
	public PagosCompanias update(PagosCompanias entity) {
		return pagoscompaniasDao.update(entity);

	}

	@Override
	public void delete(PagosCompanias entity) {
		pagoscompaniasDao.delete(entity);

	}

	@Override
	public List<PagosCompanias> findAll() {
		return pagoscompaniasDao.findAll();
	}

	@Override
	public PagosCompanias getById(Integer id) {
		return pagoscompaniasDao.findOne(id);
	}

	@Override
	public void deleteById(Integer id) {
		pagoscompaniasDao.deleteById(id);

	}

	@Override
	public DefaultResponse createOrUpdate(PagosCompaniasDto dto) {
		DefaultResponse response = new DefaultResponse();
		try {
			PagosCompanias ent = new PagosCompanias();
			BeanUtils.copyProperties(dto, ent);
			this.update(ent);
			response.setId(ent.getId());
		} catch (Exception e) {
			response.setSuccess(false);
			response.setMessage(e.getMessage());
		}
		return response;
	}

	@Override
	public List<PagosCompanias> findByName(String name) {
		return pagoscompaniasDao.findByName(name);

	}

	@Override
	public List<PagosCompanias> getPage(PaginationParams params) {
		return pagoscompaniasDao.getPage(params);
	}

	@Override
	public List<PagosCompanias> findByCompania(Integer idCompania) {
		return pagoscompaniasDao.findByCompania(idCompania);

	}

	@Override
	public List<PagosCompanias> find(PagosCompaniasDto dto) {
		return pagoscompaniasDao.find(dto);
	}

}
