/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.pagos.service;

import java.util.List;
import java.util.Map;

import com.lix.pagos.model.Pagos;
import com.lix.service.Service;
import com.lix.pagos.dto.PagosDto;
import com.lix.dto.DefaultResponse;

/**
 * Basic persistence operations for entity "Pagos"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface PagosService extends Service<Pagos,Integer>{
	DefaultResponse createOrUpdate(PagosDto dto);
	List<Pagos> findByName(String name);
}
