/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.lix.pagos.service.impl;

import java.util.List;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.lix.dto.DefaultResponse;
import com.lix.dto.PaginationParams;
import com.lix.pagos.dao.PagosDao;
import com.lix.pagos.dto.PagosDto;
import com.lix.pagos.model.Pagos;
import com.lix.pagos.service.PagosService;

/**
 * JPA implementation for basic persistence operations ( entity "Pagos" )
 * 
 * @author Telosys Tools Generator
 * 
 */

@Component("pagosService")
public class PagosServiceImpl implements PagosService {

	@Autowired
	PagosDao pagosDao;

	@Override
	public void save(Pagos entity) {
		pagosDao.save(entity);
	}

	@Override
	public Pagos update(Pagos entity) {
		return pagosDao.update(entity);

	}

	@Override
	public void delete(Pagos entity) {
		pagosDao.delete(entity);

	}

	@Override
	public List<Pagos> findAll() {
		return pagosDao.findAll();
	}

	@Override
	public Pagos getById(Integer id) {
		return pagosDao.findOne(id);
	}

	@Override
	public void deleteById(Integer id) {
		pagosDao.deleteById(id);

	}

	@Override
	public DefaultResponse createOrUpdate(PagosDto dto) {
		DefaultResponse response = new DefaultResponse();
		try {
			Pagos ent = new Pagos();
			BeanUtils.copyProperties(dto, ent);
			this.update(ent);
			response.setId(ent.getId());
		} catch (Exception e) {
			response.setSuccess(false);
			response.setMessage(e.getMessage());
		}
		return response;
	}

	@Override
	public List<Pagos> findByName(String name) {
		return pagosDao.findByName(name);

	}

	@Override
	public List<Pagos> getPage(PaginationParams params) {
		return pagosDao.getPage(params);
	}

}
