/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.secciones.dao;

import java.util.List;
import java.util.Map;
import java.util.List;
import com.lix.dao.HibernateDao;
import com.lix.secciones.model.Secciones;


/**
 * Basic persistence operations for entity "Secciones"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface SeccionesDao extends HibernateDao<Secciones,Integer> {	

	public List<Secciones> findByName(String name);
}
