
/*
 * Created on 6 dic 2013 ( Time 23:44:41 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.polizas;

import java.util.LinkedList;
import java.util.List;

import com.lix.mock.tool.MockValues;
import com.lix.polizas.model.Polizas;
import com.lix.test.clientes.ClientesMock;
import com.lix.test.companias.CompaniasMock;
import com.lix.test.secciones.SeccionesMock;

public class PolizasMock {

	private static MockValues mockValues = new MockValues();
	
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public static  Polizas createInstance() {
		Polizas entity = new Polizas();

		// Init Data fields
		entity.setNroPoliza( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setEndoso( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setObservaciones( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setFVigDesde( mockValues.nextDate() ) ; // java.util.Date 
		entity.setFVigHasta( mockValues.nextDate() ) ; // java.util.Date 
		entity.setCantCuotas( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPrima( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setSuma( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setPremio( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setTipoPoliza( SeccionesMock.createInstance() ) ; // java.lang.String 
		entity.setBienACubrir( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setMoneda( mockValues.nextString(3) ) ; // java.lang.String 
		entity.setRiesgoACubrir( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setClasePoliza( mockValues.nextString(1) ) ; // java.lang.String 
		entity.setUbicacion( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setNroChasis( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setNroMotor( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setTipoCobertura( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setFRegistracion( mockValues.nextDate() ) ; // java.util.Date 
		entity.setOrden( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPatente( mockValues.nextString(7) ) ; // java.lang.String 
		// Init Link fields (if any)
		entity.setCompanias( CompaniasMock.createInstance() ) ; // Companias 
		// setSecciones( TODO ) ; // Secciones 
		// setPagosPolizas( TODO ) ; // List<PagosCompanias> 
		entity.setClientes( ClientesMock.createInstance() ) ; // Clientes 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public static List<Polizas> createList(int count) {
		List<Polizas> list = new LinkedList<Polizas>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}	
	
}
