/*
 * Created on 27 nov 2013 ( Time 15:55:15 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.pagospolizas.service;

import java.util.List;

import com.lix.dto.DefaultResponse;
import com.lix.pagospolizas.dto.PagosPolizasDto;
import com.lix.pagospolizas.model.PagosPolizas;
import com.lix.service.Service;
import com.lix.web.Page;

/**
 * Basic persistence operations for entity "PagosPolizas"
 * 
 * 
 * @author Telosys Tools Generator
 * 
 */
public interface PagosPolizasService extends Service<PagosPolizas, Integer> {
	DefaultResponse createOrUpdate(PagosPolizasDto dto);

	List<PagosPolizas> findByName(String name);

	List<PagosPolizas> find(PagosPolizasDto dto);

	Page<PagosPolizasDto> findPage(PagosPolizasDto dto);
}
