/*
 * Created on 14 nov 2013 ( Time 17:20:08 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.secciones.dto;

import java.util.List;

import com.lix.polizas.model.Polizas;

/**
 * Dto for "Secciones"
 * 
 * @author Telosys Tools Generator
 * 
 */
public class SeccionesDto {

	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	private Integer idCompania;

	private String nombre;

	private String codigo;

	private List<Polizas> listOfPolizas;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : ID_COMPANIA ( INT )
	public void setIdCompania(Integer idCompania) {
		this.idCompania = idCompania;
	}

	public Integer getIdCompania() {
		return this.idCompania;
	}

	// --- DATABASE MAPPING : NOMBRE ( VARCHAR )
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	// --- DATABASE MAPPING : codigo ( VARCHAR )
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	public void setListOfPolizas(List<Polizas> listOfPolizas) {
		this.listOfPolizas = listOfPolizas;
	}

	public List<Polizas> getListOfPolizas() {
		return this.listOfPolizas;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

}
