/*
 * Created on 13 jul 2014 ( Time 21:03:24 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.lix.domain.master.users.dto;

import java.io.Serializable;

import com.lix.domain.master.users.dto.*;
import com.lix.dto.PaginationParams;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;



/**
 * Dto for "Users"
 *
 * @author Telosys Tools Generator
 *
 */
public class UsersDto extends PaginationParams
{
    


		    private Integer id          ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
			    private String username;

			    private String password;

			    private Boolean enabled;

    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : USERNAME ( VARCHAR ) 
    public void setUsername( String username )
    {
        this.username = username;
    }
    public String getUsername()
    {
        return this.username;
    }

    //--- DATABASE MAPPING : PASSWORD ( VARCHAR ) 
    public void setPassword( String password )
    {
        this.password = password;
    }
    public String getPassword()
    {
        return this.password;
    }

    //--- DATABASE MAPPING : ENABLED ( BIT ) 
    public void setEnabled( Boolean enabled )
    {
        this.enabled = enabled;
    }
    public Boolean getEnabled()
    {
        return this.enabled;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		return "";
		//return ReflectionToStringBuilder.toString(this);
    }

}
