/*
 * Created on 14 nov 2013 ( Time 17:20:05 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.clientes.dao.impl;

import java.util.List;

import javax.annotation.PostConstruct;

import org.hibernate.Criteria;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.lix.clientes.dao.ClientesDao;
import com.lix.clientes.model.Clientes;
import com.lix.dao.AbstractHibernateDao;

/**
 * Basic persistence operations for entity "Clientes"
 * 
 * 
 * @author Lisandro
 * 
 */
@Repository("clientesDao")
public class ClientesDaoImpl extends AbstractHibernateDao<Clientes, Integer> implements ClientesDao {

	@PostConstruct
	public void setInstance() {
		setClazz(Clientes.class);
	}

	@Override
	@Transactional
	public List<Clientes> findByName(String name) {
		Criteria criteria = getCurrentSession().createCriteria((Clientes.class));
		criteria.add(Restrictions.like("nombre", name.toUpperCase(), MatchMode.ANYWHERE));
		return (List<Clientes>) criteria.list();
	}
}
