/*
 * Created on 14 nov 2013 ( Time 17:20:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.pagos.dao.impl;

import java.util.List;

import javax.annotation.PostConstruct;

import org.hibernate.Criteria;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.lix.dao.AbstractHibernateDao;
import com.lix.pagos.dao.PagosDao;
import com.lix.pagos.model.Pagos;

/**
 * Basic persistence operations for entity "Pagos"
 * 
 *
 * @author Lisandro
 *
 */
@Repository("pagosDao")
public class PagosDaoImpl extends AbstractHibernateDao<Pagos, Integer>
		implements PagosDao {

	@PostConstruct
	public void setInstance() {
		setClazz(Pagos.class);
	}

	@Override
	@Transactional
	public List<Pagos> findByName(String name) {
		Criteria criteria = getCurrentSession().createCriteria((Pagos.class));
		criteria.add(Restrictions.like("name", name.toUpperCase(),
				MatchMode.ANYWHERE));
		criteria.setMaxResults(25);
		return (List<Pagos>) criteria.list();
	}
}
