/*
 * Created on 27 nov 2013 ( Time 15:55:18 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.lix.pagospolizas.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.lix.pagos.model.Pagos;
import com.lix.polizas.model.Polizas;

/**
 * Persistent class for entity stored in table "pagos"
 * 
 * @author Telosys Tools Generator
 * 
 */

@Entity
@DiscriminatorValue(value = "P")
public class PagosPolizas extends Pagos implements Serializable {
	private static final long serialVersionUID = 1L;

	@Column(name = "NRO_RECIBO")
	private Integer nroRecibo;

	@ManyToOne
	@JoinColumn(name = "ID_POLIZA")
	private Polizas polizas;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public PagosPolizas() {
		super();
	}

	// --- DATABASE MAPPING : NRO_RECIBO ( INT )
	public void setNroRecibo(Integer nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	public Integer getNroRecibo() {
		return this.nroRecibo;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

	public Polizas getPolizas() {
		return polizas;
	}

	public void setPolizas(Polizas polizas) {
		this.polizas = polizas;
	}

}
