/*
 * Created on 27 nov 2013 ( Time 16:23:16 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.lix.pagoscompanias.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.lix.companias.model.Companias;
import com.lix.pagos.model.Pagos;

/**
 * Persistent class for entity stored in table "pagos"
 * 
 * @author Telosys Tools Generator
 * 
 */

@Entity
@DiscriminatorValue(value = "C")
public class PagosCompanias extends Pagos implements Serializable {
	private static final long serialVersionUID = 1L;

	@Column(name = "NRO_RECIBO")
	private Integer nroRecibo;

	@ManyToOne
	@JoinColumn(name = "ID_COMPANIA", referencedColumnName = "ID", insertable = false, updatable = false)
	private Companias companias;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public PagosCompanias() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : FECHA ( DATETIME )
	// --- DATABASE MAPPING : NRO_RECIBO ( INT )
	public void setNroRecibo(Integer nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	public Integer getNroRecibo() {
		return this.nroRecibo;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		return "";
		// return ReflectionToStringBuilder.toString(this);
	}

	public Companias getCompanias() {
		return companias;
	}

	public void setCompanias(Companias companias) {
		this.companias = companias;
	}

}
