
/*
 * Created on 6 dic 2013 ( Time 23:50:03 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.secciones;

import java.util.LinkedList;
import java.util.List;

import com.lix.mock.tool.MockValues;
import com.lix.secciones.model.Secciones;
import com.lix.test.companias.CompaniasMock;

public class SeccionesMock {

	private static MockValues mockValues = new MockValues();
	
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public static  Secciones createInstance() {
		Secciones entity = new Secciones();

		// Init Data fields
		entity.setNombre( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCodigo( mockValues.nextString(5) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfPolizas( TODO ) ; // List<Polizas> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public static List<Secciones> createList(int count) {
		List<Secciones> list = new LinkedList<Secciones>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}	
	
}
