/*
 * Created on 14 nov 2013 ( Time 17:20:08 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.secciones;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import com.lix.secciones.model.Secciones;
import com.lix.secciones.service.SeccionesService;
import com.lix.test.AbstractTestWithContext;

/**
 * JUnit test case for Secciones persistence service
 * 
 * @author Telosys Tools Generator
 * 
 */
public class SeccionesTest extends AbstractTestWithContext {
	@Autowired
	SeccionesService service;

	@Test
	public void findAll() {
		List<Secciones> list = service.findAll();
		Assert.assertTrue(list.size() > 0);
	}
}
