/*
 * Created on 27 nov 2013 ( Time 15:55:15 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.pagospolizas.dao;

import java.util.List;
import java.util.Map;
import java.util.List;
import com.lix.dao.HibernateDao;
import com.lix.pagospolizas.dto.PagosPolizasDto;
import com.lix.pagospolizas.model.PagosPolizas;


/**
 * Basic persistence operations for entity "PagosPolizas"
 * 
 *
 * @author Telosys Tools Generator
 *
 */
public interface PagosPolizasDao extends HibernateDao<PagosPolizas,Integer> {	

	public List<PagosPolizas> findByName(String name);

	public List<PagosPolizas> find(PagosPolizasDto dto);
}
