
/*
 * Created on 7 dic 2013 ( Time 11:22:02 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.pagoscompanias;

import java.util.LinkedList;
import java.util.List;

import com.lix.mock.tool.MockValues;
import com.lix.pagoscompanias.model.PagosCompanias;
import com.lix.test.companias.CompaniasMock;

public class PagosCompaniasMock {

	private static MockValues mockValues = new MockValues();
	
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public static  PagosCompanias createInstance() {
		PagosCompanias entity = new PagosCompanias();

		// Init Data fields
		entity.setFecha( mockValues.nextDate() ) ; // java.util.Date 
		entity.setImporte( mockValues.nextDouble() ) ; // java.lang.Double 
//		entity.setTipoPago( mockValues.nextString(1) ) ; // java.lang.String 
		entity.setConcepto( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setNroRecibo( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setFechaVencimiento( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setPolizas( TODO ) ; // Polizas 
		entity.setCompanias(CompaniasMock.createInstance());
		// setCompanias( TODO ) ; // Companias 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public static List<PagosCompanias> createList(int count) {
		List<PagosCompanias> list = new LinkedList<PagosCompanias>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}	
	
}
