SELECT 
	polizas.id, 
	polizas.NRO_POLIZA, 
	polizas.id_cliente, 
	polizas.ENDOSO, 
	polizas.OBSERVACIONES, 
	'"' & Format([F_VIG_DESDE],"dd/mm/yyyy") & '"' AS ["F_VIG_DESDE"], 
	'"' & Format([F_VIG_HASTA],"dd/mm/yyyy") & '"' AS ["F_VIG_HASTA"], 
	polizas.CANT_CUOTAS, 
	polizas.PRIMA, 
	polizas.SUMA, 
	polizas.PREMIO, 
	polizas.TIPO_POLIZA, 
	polizas.BIEN_A_CUBRIR, 
	polizas.MONEDA, 
	polizas.RIESGO_A_CUBRIR, 
	polizas.id_compania, 
	polizas.CLASE_POLIZA, 
	polizas.UBICACION, 
	polizas.NRO_CHASIS, 
	polizas.NRO_MOTOR, 
	polizas.TIPO_COBERTURA, 
	'"' & Format([f_registracion],"dd/mm/yyyy") & '"' AS ["f_registracion"], 
	polizas.ORDEN, 
	polizas.PATENTE
FROM polizas;
