/*
 * Created on 28 nov 2013 ( Time 16:19:07 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.lix.test.polizas;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.TransactionCallback;
import org.springframework.transaction.support.TransactionTemplate;

import com.lix.dto.PaginationParams;
import com.lix.polizas.model.Polizas;
import com.lix.polizas.service.PolizasService;
import com.lix.test.AbstractTestWithContext;

/**
 * JUnit test case for Polizas persistence service
 * 
 * @author Telosys Tools Generator
 * 
 */
public class PolizasTest extends AbstractTestWithContext {
	@Autowired
	PolizasService service;

	@Autowired
	TransactionTemplate transactionTemplate;

	// @Test
	public void findAll() {
		List<Polizas> list = service.findAll();
		Assert.assertTrue(list.size() > 0);
	}

	@Test
	public void findPagos() {
		transactionTemplate.execute(new TransactionCallback<Boolean>() {

			@Override
			public Boolean doInTransaction(TransactionStatus arg0) {
				// TODO Auto-generated method stub
				PaginationParams params = new PaginationParams();
				params.setLimit(10);
				params.setStart(0);
				List<Polizas> list = service.getPage(params);
				for (Polizas p : list) {
					Assert.assertNotNull(p.getPagosPolizas());
				}
				return null;
			}
		});
	}

	@Test
	public void polizasPorCliente() {
		List<Polizas> polizas = service.polizasPorCliente(11);
		Assert.assertEquals(43, polizas.size());
	}
}
