/*
 * Created on 28 nov 2013 ( Time 16:19:02 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.lix.polizas.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.lix.clientes.model.Clientes;
import com.lix.companias.model.Companias;
import com.lix.pagospolizas.model.PagosPolizas;
import com.lix.secciones.model.Secciones;

/**
 * Persistent class for entity stored in table "polizas"
 * 
 * @author Telosys Tools Generator
 * 
 */

@Entity
@Table(name = "polizas")
public class Polizas implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", nullable = false)
	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "NRO_POLIZA", length = 20)
	private String nroPoliza;

	@Column(name = "ENDOSO", length = 20)
	private String endoso;

	@Column(name = "OBSERVACIONES", length = 100)
	private String observaciones;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VIG_DESDE")
	private Date fVigDesde;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_VIG_HASTA")
	private Date fVigHasta;

	@Column(name = "CANT_CUOTAS")
	private Integer cantCuotas;

	@Column(name = "PRIMA")
	private Double prima;

	@Column(name = "SUMA")
	private Double suma;

	@Column(name = "PREMIO")
	private Double premio;

	@Column(name = "BIEN_A_CUBRIR", length = 40)
	private String bienACubrir;

	@Column(name = "MONEDA", length = 3)
	private String moneda;

	@Column(name = "RIESGO_A_CUBRIR", length = 50)
	private String riesgoACubrir;

	@Column(name = "CLASE_POLIZA", length = 1)
	private String clasePoliza;

	@Column(name = "UBICACION", length = 100)
	private String ubicacion;

	@Column(name = "NRO_CHASIS", length = 50)
	private String nroChasis;

	@Column(name = "NRO_MOTOR", length = 50)
	private String nroMotor;

	@Column(name = "TIPO_COBERTURA", length = 50)
	private String tipoCobertura;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_registracion")
	private Date fRegistracion;

	@Column(name = "ORDEN")
	private Integer orden;

	@Column(name = "PATENTE", length = 7)
	private String patente;

	// "idCliente" (column "id_cliente") is not defined by itself because used
	// as FK in a link
	// "idCompania" (column "id_compania") is not defined by itself because used
	// as FK in a link
	// "seccionId" (column "SECCION_ID") is not defined by itself because used
	// as FK in a link
	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@ManyToOne
	@JoinColumn(name = "id_compania", referencedColumnName = "ID", insertable = false, updatable = false)
	private Companias companias;

	@OneToMany(mappedBy = "polizas", targetEntity = PagosPolizas.class)
	private List<PagosPolizas> pagosPolizas;

	@ManyToOne
	@JoinColumn(name = "id_cliente", referencedColumnName = "id", insertable = false, updatable = false)
	private Clientes clientes;
	@ManyToOne
	@JoinColumn(name = "seccion_id", referencedColumnName = "id", insertable = false, updatable = false)
	private Secciones tipoPoliza;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public Polizas() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : NRO_POLIZA ( VARCHAR )
	public void setNroPoliza(String nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	public String getNroPoliza() {
		return this.nroPoliza;
	}

	// --- DATABASE MAPPING : ENDOSO ( VARCHAR )
	public void setEndoso(String endoso) {
		this.endoso = endoso;
	}

	public String getEndoso() {
		return this.endoso;
	}

	// --- DATABASE MAPPING : OBSERVACIONES ( VARCHAR )
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	// --- DATABASE MAPPING : F_VIG_DESDE ( DATETIME )
	public void setFVigDesde(Date fVigDesde) {
		this.fVigDesde = fVigDesde;
	}

	public Date getFVigDesde() {
		return this.fVigDesde;
	}

	// --- DATABASE MAPPING : F_VIG_HASTA ( DATETIME )
	public void setFVigHasta(Date fVigHasta) {
		this.fVigHasta = fVigHasta;
	}

	public Date getFVigHasta() {
		return this.fVigHasta;
	}

	// --- DATABASE MAPPING : CANT_CUOTAS ( INT )
	public void setCantCuotas(Integer cantCuotas) {
		this.cantCuotas = cantCuotas;
	}

	public Integer getCantCuotas() {
		return this.cantCuotas;
	}

	// --- DATABASE MAPPING : PRIMA ( DOUBLE )
	public void setPrima(Double prima) {
		this.prima = prima;
	}

	public Double getPrima() {
		return this.prima;
	}

	// --- DATABASE MAPPING : SUMA ( DOUBLE )
	public void setSuma(Double suma) {
		this.suma = suma;
	}

	public Double getSuma() {
		return this.suma;
	}

	// --- DATABASE MAPPING : PREMIO ( DOUBLE )
	public void setPremio(Double premio) {
		this.premio = premio;
	}

	public Double getPremio() {
		return this.premio;
	}

	// --- DATABASE MAPPING : TIPO_POLIZA ( VARCHAR )
	public void setTipoPoliza(Secciones tipoPoliza) {
		this.tipoPoliza = tipoPoliza;
	}

	public Secciones getTipoPoliza() {
		return this.tipoPoliza;
	}

	// --- DATABASE MAPPING : BIEN_A_CUBRIR ( VARCHAR )
	public void setBienACubrir(String bienACubrir) {
		this.bienACubrir = bienACubrir;
	}

	public String getBienACubrir() {
		return this.bienACubrir;
	}

	// --- DATABASE MAPPING : MONEDA ( VARCHAR )
	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getMoneda() {
		return this.moneda;
	}

	// --- DATABASE MAPPING : RIESGO_A_CUBRIR ( VARCHAR )
	public void setRiesgoACubrir(String riesgoACubrir) {
		this.riesgoACubrir = riesgoACubrir;
	}

	public String getRiesgoACubrir() {
		return this.riesgoACubrir;
	}

	// --- DATABASE MAPPING : CLASE_POLIZA ( VARCHAR )
	public void setClasePoliza(String clasePoliza) {
		this.clasePoliza = clasePoliza;
	}

	public String getClasePoliza() {
		return this.clasePoliza;
	}

	// --- DATABASE MAPPING : UBICACION ( VARCHAR )
	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	// --- DATABASE MAPPING : NRO_CHASIS ( VARCHAR )
	public void setNroChasis(String nroChasis) {
		this.nroChasis = nroChasis;
	}

	public String getNroChasis() {
		return this.nroChasis;
	}

	// --- DATABASE MAPPING : NRO_MOTOR ( VARCHAR )
	public void setNroMotor(String nroMotor) {
		this.nroMotor = nroMotor;
	}

	public String getNroMotor() {
		return this.nroMotor;
	}

	// --- DATABASE MAPPING : TIPO_COBERTURA ( VARCHAR )
	public void setTipoCobertura(String tipoCobertura) {
		this.tipoCobertura = tipoCobertura;
	}

	public String getTipoCobertura() {
		return this.tipoCobertura;
	}

	// --- DATABASE MAPPING : f_registracion ( DATETIME )
	public void setFRegistracion(Date fRegistracion) {
		this.fRegistracion = fRegistracion;
	}

	public Date getFRegistracion() {
		return this.fRegistracion;
	}

	// --- DATABASE MAPPING : ORDEN ( INT )
	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Integer getOrden() {
		return this.orden;
	}

	// --- DATABASE MAPPING : PATENTE ( VARCHAR )
	public void setPatente(String patente) {
		this.patente = patente;
	}

	public String getPatente() {
		return this.patente;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(this.getNroPoliza());
		sb.append(" - ");
		if (this.getTipoPoliza() != null) {
			sb.append(this.getTipoPoliza().getNombre());
		}
		// String toString = this.getNroPoliza() + "-" + this.getTipoPoliza() !=
		// null ? this
		// .getTipoPoliza().getNombre() : "null";
		return sb.toString();
		// return ReflectionToStringBuilder.toString(this);
	}

	public Date getfVigDesde() {
		return fVigDesde;
	}

	public void setfVigDesde(Date fVigDesde) {
		this.fVigDesde = fVigDesde;
	}

	public Date getfVigHasta() {
		return fVigHasta;
	}

	public void setfVigHasta(Date fVigHasta) {
		this.fVigHasta = fVigHasta;
	}

	public Date getfRegistracion() {
		return fRegistracion;
	}

	public void setfRegistracion(Date fRegistracion) {
		this.fRegistracion = fRegistracion;
	}

	public Companias getCompanias() {
		return companias;
	}

	public void setCompanias(Companias companias) {
		this.companias = companias;
	}

	public List<PagosPolizas> getPagosPolizas() {
		return pagosPolizas;
	}

	public void setPagosPolizas(List<PagosPolizas> pagosPolizas) {
		this.pagosPolizas = pagosPolizas;
	}

	public Clientes getClientes() {
		return clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
